name: Apply terraform changes

on:
  pull_request:
    branches: [main]

jobs:
  apply:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: dflook/terraform-apply@v1
        with:
          variables: |
            github_token = "${{ secrets.github_token }}"