name: Apply terraform changes

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: dflook/terraform-apply@v1
        env:
          gh_token: ${{ secrets.gh_token }}
          
