name: Format Terraform files

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Format Terraform files
        uses: dflook/terraform-fmt@v1

      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.ref_name }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Format files
          default_author: github_actions
