name: Apply terraform changes

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: self-hosted
    env:
      GITHUB_TOKEN: ${{ secrets.gh_token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Apply terraform
        uses: dflook/terraform-apply@v1
        with:
          auto_approve: true
          variables: |
            gh_token = "${{ secrets.gh_token }}"
            
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Save changes
          add: '--update'
          committer_name: actions
          committer_email: actions@github.com
          pull: '--ff'
