name: Format Terraform files

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Format Terraform files
        uses: dflook/terraform-fmt@v1

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Format files
          committer_name: actions
          committer_email: actions@github.com
